id: A41A8B74E
title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
  of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:22:34.629282
  last_modified_at: 2022-03-01 03:22:34.629285
