id: A41A8B74E
title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha Thangtong
  Gyalpo's Lifetime as Bhikṣu Padma Karpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:22:34.632366
  last_modified_at: 2022-03-01 03:22:34.632369
