id: A41A8B74E
title: Prayer to the Lineage of Parting from the Four Attachments
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:22:34.626998
  last_modified_at: 2022-03-01 03:22:34.627007
